### ISSUE TITLE
ComplyChain Application Name on My iPad is Do Good.

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Ilab-do-good#1]
The ComplyChain application the name is still called Do Good on my iPad. The icon has some weird or default icon.

Not sure why it's called Do Good and not ComplyChain.

Are you planning on adding an icon?

My testing is being done on our iPad Air 2 (iOS 10.3.3) because our iPod Touch 5th Generation (iOS 9.3.5) opens the application but displays a blank screen.

**Comment by adriennerlong** [comment]
We have alerted the developers that the app name changed to Comply Chain. They have also been provided with the app icons. Please close out on this issue.

**Comment by jfc3-dol** [comment]
@adriennerlong,

As a rule we will close issue once we see that it is fixed.

**Comment by jfc3-dol** [comment]
Closing this issues since it's been corrected to now display "ComplyChain" in the header section on all the screens I looked at instead of saying "Do Good".
