### ISSUE TITLE
ILAB ComplyChain Application Title is Do Good

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Ilab-do-good#10]
In the middle of the header section of the application it says "Do Good" instead of ComplyChain".

**NOTE** - My testing is being done on our iPad Air 2 (iOS 10.3.3) because our iPod Touch 5th Generation (iOS 9.3.5) opens the application but displays a blank screen.

**Comment by adriennerlong** [comment]
We have alerted the developers that the app name changed to Comply Chain. Please close out on this issue in the next testing.

**Comment by jfc3-dol** [comment]
@adriennerlong,

As a rule we will close issue once we see that it is fixed.

**Comment by jfc3-dol** [comment]
Closing this issues since it's been corrected to now display "ComplyChain" in the header section on all the screens I looked at instead of saying "Do Good".
