### ISSUE TITLE
ComplyChain Will Not Open in Our Ipod Touch 5th Generation

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Ilab-do-good#11]
My testing is being done on our iPad Air 2 (iOS 10.3.3) because our iPod Touch 5th Generation (iOS 9.3.5) opens the application but displays a blank screen.

Not sure if the application is only built for newer version of iOS or it 's having trouble open on the older device from I think 2012 or so.

**Comment by adriennerlong** [comment]
This is a low priority issue. We will ask developers to address before 9/11, if possible.

**Comment by jfc3-dol** [comment]
@adriennerlong,

Thought you want all users to be able to down load the application and then use it. Not only the those with the newest devices and software.

People will then rate the application poorly if they can't use it because it won't open or crashes when they do certain tasks.

**Comment by jfc3-dol** [comment]
Keeping this issue open until we can open and test application in our older device with iOS 9.3.5 operating system which is one version behind at this time.

@adriennerlong,

I think we might want to mention in the Apple iTunes Store which operating system the application works in, so people don't download it for the older ones it doesn't work on currently.

**Comment by adriennerlong** [comment]
Thanks for raising this issue. We will definitely want to mention the os requirements in the app stores.  Is that the only reason why the application won't run properly on older devices?

**Comment by jfc3-dol** [comment]
@adriennerlong,

The note or telling the user what versions it works with only warns the user not to download if they are using older version of the operating system.

It won't prevent them from doing so but I'm not positive about that.

@giridhar,

Can the Apple iTunes Store prevent people with older devices that have older versions of the operating system downloading the application?

**Comment by jfc3-dol** [comment]
@adriennerlong,

ComplyChain now opens on our iPod but displays the Steps image/icons and now of them are tap able to allow people to go to the content.

Leaving this issues open until it is fixed or it's decided that the application will not be available to old versions of the operating system.

The iPod is using iOS 9.3.5 operating system which is one version behind at this time. After Apple announces there new products the newer iOS version 11 will most likely be made available to people. Currently, they are testing version 11.

**Comment by adriennerlong** [comment]
From ICF: On hold, we don't have the hardware to debug the issue. 

From ILAB: Can we put a disclaimer in the iTunes store that the app doesn’t work with certain versions of ios? We’ve noticed that the app has problems on older versions, but appears to work well on 10.3

**Comment by jfc3-dol** [comment]
@giridhar,

Doesn't iTunes Store allow you to certain versions or from a certain version newer to download the application?

**Comment by jfc3-dol** [comment]
I'm going to close this issue because I'm assuming we have prevented order operating system that can't run the application from downloading it.
