### ISSUE TITLE
Functional - Web - Changing Languages Brings Person Back to Home Page

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Ilab-do-good#110]
While in the middle of the application and a person changes languages it brings the person back to the home page, instead of leaving them where they are before changing the language.

An example of why this is a problem would occur when one person is looking for certain content and then changes languages for someone that doesn't speak the current language.

**Comment by sanganalakshay** [comment]
Fixed in the latest commit

**Comment by jfc3-dol** [comment]
I switched the pages languages for IE 11, Firefox, and Chrome on different pages and the ComplyChain application stayed on that page instead of going back to the home page for the new language.

Closing issue.
