### ISSUE TITLE
Functional - iOS - Changing Languages Brings Person Back to Home Screen

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Ilab-do-good#111]
While in the middle of the application and a person changes languages it brings the person back to the home screen, instead of leaving them where they are before changing the language.

An example of why this is a problem would occur when one person is looking for certain content and then changes languages for someone that doesn't speak the current language.

**Comment by sanganalakshay** [comment]
fixed in the latest commit

**Comment by jfc3-dol** [comment]
ComplyChain iOS application now stays on a given screen when you change languages and doesn't go back to the home screen.

Closing issue.
