### ISSUE TITLE
Functional - Web - Step 2 Topic 2 Page Incorrect Link

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Ilab-do-good#112]
The Spanish Step 2 Topic 2 screen has a link that starts at the end of the second paragraph and goes to the end of the forth. See French and Spanish screenshots showing the difference.

**Comment by sanganalakshay** [comment]
fixed

**Comment by jfc3-dol** [comment]
The link on the Spanish Steps 2 Topic 2 screen has been fixed.

See the screenshot below.

![compychain - web - spanish - step 2 topic 2 link fixed](https://user-images.githubusercontent.com/10423487/43423276-f5622ec8-9419-11e8-89e9-24361399927d.png)

Closing issue.
