### ISSUE TITLE
Functional - Web - IE Not Loading Home Page Correctly

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Ilab-do-good#113]
The last update is not allowing IE to load the home page correctly/completely. Not sure why I get the "Loading Resources..." spinning icon even though the page loads below it after a bunch of time.

See the attached screenshot.

![complychain - firefox - home page](https://user-images.githubusercontent.com/10423487/43530866-917de956-957c-11e8-98f4-936c4485f628.png)

**Comment by jfc3-dol** [comment]
I am using IE 11.0.9 to do my testing which I don't believe has been updated in a long time.

I used to be able to load the application in Chrome and Firefox too previously to the last update.

**Comment by sanganalakshay** [comment]
should be fixed

**Comment by jfc3-dol** [comment]
Will test when we get the next code push.

It was weird that it worked the time before but not this last time.

**Comment by jfc3-dol** [comment]
At times when switching languages or first loading the page it's slow in IE 11 and Firefox but they at least load now.

I'm going to close this issue.
