### ISSUE TITLE
Functional - iOS - When Searching for "Plan" Application Goes to Page with "Plan" on It

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Ilab-do-good#119]
When I search for the word "plan" the application on iOS quickly shows the search results screen and the goes to the "Step 6: Remediate Violations" screen which must have the word "plan" in it.

In last years version of the application, this did not happen. I'm wondering if there is only one result for the word "plan" so it's sending it to that one page. Not a result I would expect and highly unlikely that there is only one screen with the word "plan" in it.

The same thing happens for the website too and even for French and Spanish too.

Will create an issue for the web application too so we make sure we test it in both, but my guess is there is one fix for both.

**Comment by sanganalakshay** [comment]
In the current live version ... if you search for 'plan', it directly sends you to the "Step 6: Remediate Violations" screen.

This has been the behavior ever since the app is live, that whenever there is only one result found it directly takes you to page containing the searched item..

**Comment by sanganalakshay** [comment]
is this issue same as #120 issue?

**Comment by jfc3-dol** [comment]
One of these should be for the web which I changed #120 to be.

Hadn't closed this one because I was working on the updated web issues and not the iOS issues.

Closing now because the same logic applies to both that if a person searches for something and there is only one result, it goes to that page.
