### ISSUE TITLE
Functional - iOS - When Searching for "Plan" Application Goes to Page with "Plan" on It

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Ilab-do-good#120]
When I search for the word "plan" the application on the website quickly shows the search results screen and the goes to the "Step 6: Remediate Violations" screen which must have the word "plan" in it.

In last years version of the application, this did not happen. I'm wondering if there is only one result for the word "plan" so it's sending it to that one page. Not a result I would expect and highly unlikely that there is only one screen with the word "plan" in it.

The same thing happens for the website too and even for French and Spanish too.

**Comment by sanganalakshay** [comment]
should be fixed in the latest code push

**Comment by jfc3-dol** [comment]
Okay, guess I never did a search that only found one results and then went directly to that page. There is a redirect from the research results page to the one answer.

I'm closing this issue.
