### ISSUE TITLE
Functional - Web - Page Missing Breadcrumb Navigation and Search Button after Searching

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Ilab-do-good#121]
After searching for the word "plan" the page jumps to the only search result page it found. It's missing the breadcrumb navigation and the search button. The problem showed up for Spanish and in French.

Please look at the two screenshots below.

After searching for plan.

![complychain - web - missing breadcrumb navigation and search button after search](https://user-images.githubusercontent.com/10423487/43662201-1c2121f6-9733-11e8-9915-12b8b20b7bc4.png)

After following links to navigate to the page.

![complychain - web - breadcrumb navigation and search button after following links](https://user-images.githubusercontent.com/10423487/43662205-1f182742-9733-11e8-8a76-6bda3f89f5f0.png)

**Comment by sanganalakshay** [comment]
should be fixed in the latest code push

**Comment by jfc3-dol** [comment]
The problem of no breadcrumbs showing up for English, Spanish, and French pages has been fixed for the web version. It's also working on the iOS application.

I'm closing this issue.
