### ISSUE TITLE
Accessibility - Menu Button Doesn't Tell Purpose

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Ilab-do-good#14]
The main menu button does not tell the screen reader (VocieOver) user what the purpose of the button is.

It should tell the user that it is a menu button. Plus, if it is open/expanded or closed.

I am assuming this will be an issues on all screens.

**Comment by adriennerlong** [comment]
I've flagged this as a high priority issue. We will ask the developers to address before 9/11.

**Comment by jfc3-dol** [comment]
@adriennerlong,

Thanks, for getting them to fix this item. It's important for those using screen readers.

**Comment by jfc3-dol** [comment]
I'm closing this issue because the main menu tells the user now that it is a button and for the menu.

There are other issues I found and opened related to the main menu.
