### ISSUE TITLE
Accessibility - Three Items Under Header Not Saying They are Links/Buttons

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Ilab-do-good#17]
The three navigation related items under the header section is not telling the screen reader user they are links or buttons.

Without tell the screen reader user they are links or buttons they will not know there is content somewhere else in the application.

**Comment by jfc3-dol** [comment]
The problem includes the icons and the text that follows them.

**Comment by adriennerlong** [comment]
I've flagged this as a high priority issue. We will ask the developers to address before 9/11.

**Comment by jfc3-dol** [comment]
Closing issues because VoiceOver users are now notified that these three items are links.
