### ISSUE TITLE
Accessibility - Magnifying Glass Says it Can be Toggled but Not What It's Function

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Ilab-do-good#19]
The magnifying glass ways it can be toggled but not what it's function is such as "Search" in this case.

I didn't even see the search button the first few times I looked at the page until VoiceOver (screen reader) read it to me.

**Comment by adriennerlong** [comment]
I've flagged this as a high priority issue. We will ask the developers to address before 9/11.

**Comment by jfc3-dol** [comment]
@adriennerlong,

Thanks, for getting the developers to fix this item. It's important for those using screen readers.

**Comment by jfc3-dol** [comment]
Thanks, for fixing the search icon so it now tells screen reader user that the items is for search.

The outstanding issues is when tapped the screen reader user is not notified it opened. Along with the users focus does not go to the search INPUT field to make it easier for them to start entering information.

**Comment by adriennerlong** [comment]
ICF, please enable screen reader to be notified when the search field is opened.

**Comment by adriennerlong** [comment]
Second part is related to Issue #24 ICF, please have the cursor focus in the input field.

**Comment by jfc3-dol** [comment]
@adriennerlong,

After tapping the Search button it opens the search section and focuses the user there but doesn't mention it's an edit field and can type text in it.

At least for the pages I tried except the Home screen did not focus the cursor to the search box. It's saying it's checked which is strange.

**Comment by jfc3-dol** [comment]
Being a toggle button is a bit confusing for the search button but now at least it tells the user of TalkBack what it's function is.

**Comment by jfc3-dol** [comment]
The Home screen did not focus the cursor to the search box using TalkBack.

It's saying it's checked which is strange.

**Comment by adriennerlong** [comment]
From ICF: #19: Initial issue is fixed, input not being focused is issue #24

**Comment by jfc3-dol** [comment]
VoiceOver now announces that it's "Search toggle button not pressed double tap to toggle setting".

Bit confusing but at least it tells you what the button is and how to use it.

Removing iOS label and will check that the same thing happens for Android and the web versions.

**Comment by jfc3-dol** [comment]
TalkBack now announces that it's "Search checked toggle button double tap to toggle".

Bit confusing but at least it tells you what the button is and how to use it.

Removing TalkBack label and will check that the same thing happens for the web version.

**Comment by jfc3-dol** [comment]
JAWS reads "Search toggle button'.

Removing web label and will close issue.
