### ISSUE TITLE
Steps 5 - 8 Have Same Content as Step 4

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Ilab-do-good#2]
We noticed that steps five through eight have the same content as step four.

My testing is being done on our iPad Air 2 (iOS 10.3.3) because our iPod Touch 5th Generation (iOS 9.3.5) opens the application but displays a blank screen.

**Comment by adriennerlong** [comment]
The app developers did not yet build pages for Steps 5-8. Please close out on this issue.

**Comment by jfc3-dol** [comment]
@adriennerlong,

As a rule we will close issue once we see that it is fixed.

**Comment by jfc3-dol** [comment]
I'm closing this issues because now steps 5 - 8 have different content than step 4. 

Will need to check these new screens and those related to them are accessible once I get through the rest of the open GitHub issues for the iOS ComplyChain application.
