### ISSUE TITLE
Accessibility - Not Enough Color Contrast for Search Icon

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Ilab-do-good#23]
While testing didn't notice search icon because there was not enough color contrast between it and background that it is on top of.

I didn't realize the application had a search function.

**Comment by adriennerlong** [comment]
I've flagged this as a high priority issue. We will ask the developers to address before 9/11.

**Comment by jfc3-dol** [comment]
@adriennerlong,

Thanks, for getting the developers to fix this item. It's important for those with low vision and certain type of colorblindness.

**Comment by jfc3-dol** [comment]
Thanks, for improving the color contrast of the icon so people can see it easier.

I'm closing the issue.
