### ISSUE TITLE
Accessibility - Search Results Screen Content is Left-aligned to Left Edge of Screen

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Ilab-do-good#26]
While testing the search function I noticed the search results screens content is left-aligned to left edge of screen making it difficult to read.

**Comment by adriennerlong** [comment]
I've flagged this as a low priority issue. We will ask the developers to address before 9/11, if possible.

**Comment by jfc3-dol** [comment]
@adriennerlong,

Thanks, for getting the developers to fix this item. It's important for those with visual issues.

**Comment by jfc3-dol** [comment]
Thanks, for moving the search results over to the right a bit can you have it align with the left-side of the search box above to give it a bit more room?

**Comment by adriennerlong** [comment]
Thanks for the suggestion. Marking as a low priority issue. ICF, please address before 9/11 if time allows.

**Comment by jfc3-dol** [comment]
@adriennerlong,

The search results are not as close to the left-hand side of the screen so it's easier for people to read the content.

Closing issue.
