### ISSUE TITLE
Header Section has Miscellaneous Extra Text

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Ilab-do-good#3]
While testing I noticed there is text displaying behind the application header section text. It looks to be the device name, if wifi is on, the time, and battery information.

Think the application header section needs to moved down so the application header shows content properly.

**NOTE** - My testing is being done on our iPad Air 2 (iOS 10.3.3) because our iPod Touch 5th Generation (iOS 9.3.5) opens the application but displays a blank screen.

**Comment by adriennerlong** [comment]
The developers are aware of this problem. Please close out on this in next testing.

**Comment by jfc3-dol** [comment]
@adriennerlong,

As a rule we will close issue once we see that it is fixed.

**Comment by jfc3-dol** [comment]
@adriennerlong,

Attached is a screenshot showing the over lapping text.

![complychain - on all wscreens the device type time and battery percentage are covered up by complychain header information](https://user-images.githubusercontent.com/10423487/29829460-80f5ed64-8cad-11e7-9637-e7dff20ad1ce.png)

**Comment by jfc3-dol** [comment]
Closing this issue because the miscellaneous other header area information about the device is no longer showing on any of the screens I checked.
