### ISSUE TITLE
Accessibility -  "Basics of a Social Compliance System" Screen - Skips "Home" Bread Crumb

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Ilab-do-good#30]
While using VoiceOver it skips over reading the "Home" bread crumb when reading down the page.

**Comment by adriennerlong** [comment]
I've flagged this as a high priority issue. We will ask the developers to address before 9/11.

**Comment by jfc3-dol** [comment]
@adriennerlong,

Thanks, for getting the developers to fix this item. It's important for those using screen readers.

**Comment by jfc3-dol** [comment]
Thanks, for making the "Home" link say it's a home link.
