### ISSUE TITLE
Accessibility - Main Steps Screen - Skips "Home" Bread Crumb

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Ilab-do-good#34]
While using VoiceOver it skips over reading the "Home" bread crumb when reading down the page.

**Comment by adriennerlong** [comment]
I've flagged this as a high priority issue. We will ask the developers to address before 9/11.

**Comment by jfc3-dol** [comment]
@adriennerlong,

Thanks, for getting the developers to fix this item. It's important for those using screen readers.

**Comment by jfc3-dol** [comment]
Thanks, for fixing the "Home" link so it is read by VoiceOver.

Closing issue.
