### ISSUE TITLE
Home Link in Nagiation Does Not Work

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Ilab-do-good#4]
When I open the navigation to go to new section or part of the application and attempt to tap on the "Home" text it takes me nowhere.

Is this not supposed to do that  because I would expect it do so.

**NOTE** - My testing is being done on our iPad Air 2 (iOS 10.3.3) because our iPod Touch 5th Generation (iOS 9.3.5) opens the application but displays a blank screen.

**Comment by adriennerlong** [comment]
You're correct, it should direct you to the home page. The developers are aware of this issue. Please close out on next testing.

**Comment by jfc3-dol** [comment]
@adriennerlong,

As a rule we will close issue once we see that it is fixed.

**Comment by jfc3-dol** [comment]
Closing this issue because the "Home" link in the navigation menu takes me back to the main screen from any of the screens I tested it on.
