### ISSUE TITLE
No Easy Way to Go Back to Previous Topic under Steps Section

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Ilab-do-good#40]
There is no easy way to go back to the previous Topics screen under the Steps section of the application.

There might be other places this is a problem.

**Comment by adriennerlong** [comment]
I've flagged this as a low priority issue. We will ask the developers to address before 9/11, if possible.

**Comment by jfc3-dol** [comment]
@adriennerlong,

Thanks, for getting the developers to fix this item. It's important for those using screen readers and others too.

**Comment by jfc3-dol** [comment]
Thanks, for adding the ability to move between sections or topics within those sections.

Leaving open until I can make sure I can pick the topic I want to look at which I can not do currently with VoiceOver.

**Comment by jfc3-dol** [comment]
@adriennerlong,

Thanks, for adding the navigation to go back to a previous Step or to the next Topic and so on.

Closing issue.
