### ISSUE TITLE
Functional - Rogue Period on Step 4 Topic 4 Screen

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Ilab-do-good#41]
While looking at the Step 4 Topic Screens I notice there is rogue period after the first paragraph on on the first screen.

**Comment by adriennerlong** [comment]
Could you send a screen shot? I can't find the rogue period.

**Comment by jfc3-dol** [comment]
@adriennerlong,

Attached is the screenshot showing the rogue period between paragraphs.

![complychain - step 4 topic 4 - rogue period between paragraphs](https://user-images.githubusercontent.com/10423487/29829396-536af042-8cad-11e7-9b74-9ebe67825d4e.png)

**Comment by jfc3-dol** [comment]
Closing this issue because the rogue period between paragraphs has been removed.
