### ISSUE TITLE
ComplyChain Icon Not Showing on iPad

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Ilab-do-good#45]
While looking at the iPad to get ready to test, I noticed the icon is a default icon instead of the ComplyChain icon that show on the iPod on the application screens of both devices.

Mentioned it to @giridhar and he thinks you need to set the icon to show for the different size or type of devices, or that's what I understood from what he said.

**Comment by adriennerlong** [comment]
ICF, let me know if you need the graphic designer to provide different sizes of the icon

**Comment by jfc3-dol** [comment]
@adriennerlong,

The ComplyChain icon is still not displaying on the iPad application screens. Guessing the write size or device icon is not available to the device.

**Comment by adriennerlong** [comment]
From ICF: Fixed

**Comment by jfc3-dol** [comment]
The ComplyChain icon shows on the iPad and our new iPhone 7, so I'm closing the issue.
