### ISSUE TITLE
Accessibility - Main Menu Steps - VoiceOver Reads Steps but Can Not Activate Them

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Ilab-do-good#49]
VoiceOver will not let me activate the different Step buttons/links. VoiceOver reads them one after the other and then says button at the end which if tapped does nothing.

**Comment by jfc3-dol** [comment]
@adriennerlong,

I can now activate the menu items with VoiceOver but when I open a given Step and the look at the Topics under that Step all the other Steps are visible.

Opening a new ticket for that issue but this open is not closed because there are still issues.

**Comment by adriennerlong** [comment]
From ICF: Fixed

**Comment by jfc3-dol** [comment]
Closing this issue because I can now activate the individual topics under the steps and go to those screens.
