### ISSUE TITLE
Bread Crumbs Display to Close to Left Screen Edge

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Ilab-do-good#5]
The bread crumbs display to close to the left edge. The problem is showing up on all the pages.

See the following screens as an example.

- About this toolkit
- What are Forced Labor and Child Labor
- Steps

**NOTE** - My testing is being done on our iPad Air 2 (iOS 10.3.3) because our iPod Touch 5th Generation (iOS 9.3.5) opens the application but displays a blank screen.

**Comment by adriennerlong** [comment]
We have categorized this as a low priority issue. Will ask developers to resolve before 9/11, if possible.

**Comment by jfc3-dol** [comment]
@adriennerlong,

For those that have mobility and dexterity issues having the link so close to the left edge of the screen makes it difficult to tap on.

It's a simple CSS change of adding 10 or 15 pixels to the left margin.

**Comment by jfc3-dol** [comment]
Thanks, for moving it over. 

Can you have the bread crumbs line up with the heading below the bread crumbs? Thinking you need another 15 or 20 pixels but not sure when looking at it on a mobile or handheld device.

**Comment by adriennerlong** [comment]
Thanks for your comment, John. We'll categorize this as a low priority issue for now and try to address before 9/11.

**Comment by jfc3-dol** [comment]
@adriennerlong,

Looks like the bread crumbs have been moved to the right enough to allow the user to read them easier along with giving them room to tap on them.

Closing the issue.
