### ISSUE TITLE
Search Results Screen - VoiceOver Not Allowing Links to be Activated

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Ilab-do-good#52]
VoiceOver also isn't allowing me to activate any of the link on the search results page.

**Comment by jfc3-dol** [comment]
@adriennerlong,

When I move the focus manually with my finger to the links I can then double tap to open them. The problem is that when search results are found the focus does not go to the results so a person can activate the links. The test is read as plain test and not as links.

**Comment by adriennerlong** [comment]
From ICF: Fixed

**Comment by jfc3-dol** [comment]
I can activate the search results links with VoiceOver, so I'm closing the issue.
