### ISSUE TITLE
Main Menu - "What are Child Labor and Forced Labor" Link Not Working

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Ilab-do-good#53]
VoiceOver is not opening the "What are Child Labor and Forced Labor" link in the main menu when it's tapped. The text gets made bold but it does not go to the correct screen. It works fine without VoiceOver.

**Comment by jfc3-dol** [comment]
@adriennerlong,

VoiceOver is reading it as a links but not opening the screen.

**Comment by jfc3-dol** [comment]
VoiceOver is reading the link and allowing it to go to the proper screen but not reading past the first heading.

**Comment by adriennerlong** [comment]
From ICF: Fixed

**Comment by jfc3-dol** [comment]
I am now able to activate the "What are Child Labor and Forced Labor" link and go to the screen using VoiceOver.

Closing issue.
