### ISSUE TITLE
Accessibility - Steps Screens - Not Able to Open or Close Sections Content with VoiceOver

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Ilab-do-good#55]
While using VoiceOver I'm not able to tap on the items that display content such as Learning Objectives, Key Terms, Topics, or Further Resources.

By having all the content hidden behind the toggle button  VoiceOver user s will not be able to see any of this content. The screen comes with all the items closed and not showing content which as I have stated makes the content inaccessible to VoiceOver users because they can't open the information.

**Comment by jfc3-dol** [comment]
@adriennerlong.

I'm able to open and close the sections with VoiceOver but it only reads "expand content toggle button not pressed double tap to toggle setting." I'm never told what the toggle is for such as "Key Terms" or "Topics", etc.

**Comment by jfc3-dol** [comment]
Issue applies to both iOS and Android along with the website.

**Comment by adriennerlong** [comment]
From ICF: Fixed

**Comment by jfc3-dol** [comment]
I'm now able with VoiceOver on the iOS version to open and close the hidden content. I have removed the iOS label and will do the same once I can test the web and Android version.

**Comment by jfc3-dol** [comment]
I'm now able with TalkBack on the Android version to open and close the hidden content. I have removed the Android label and will do the same once I can test the web version.

**Comment by jfc3-dol** [comment]
I'm now able with JAWS on the web version to open and close the hidden content. I have removed the web label and will be closing the issue.
