### ISSUE TITLE
Step 6 - There is No Content Under Further Resources

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Ilab-do-good#56]
When looking at the updated Steps 5 - 8 I noticed that for the main Step 6 screen under the Further Resources section there is no content except for a footnote which I believe is on the main Step screens in that section.

**Comment by adriennerlong** [comment]
ICF, please delete the Further Resources tab on the main Steps 6 page (there are no resources to list). The footnote information should be moved to the bottom of the Communication About Remediation topic.

**Comment by jfc3-dol** [comment]
@adriennerlong,

Closing issue since "Further Resources" section for Step 6 is now removed.
