### ISSUE TITLE
Three Pieces of Navigation showing on Home Screen

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Ilab-do-good#6]
Is there a reason why there are what look like three pieces of navigation showing on the home screen?

**NOTE** - My testing is being done on our iPad Air 2 (iOS 10.3.3) because our iPod Touch 5th Generation (iOS 9.3.5) opens the application but displays a blank screen.

**Comment by adriennerlong** [comment]
The 3 pieces of navigation are intentional. We want users to explore the background information on social compliance systems before they get into the 8 steps. Please close out on this issue.

**Comment by jfc3-dol** [comment]
@adriennerlong,

As a rule we will close issue once we see that it is fixed.

If I remember correctly, one of those items is the eight steps.

**Comment by jfc3-dol** [comment]
@adriennerlong,

Okay, if that is the reasoning I will close the issue. Wanted to make sure it was done for a reason and not an issue when creating the iOS application from the other code.
