### ISSUE TITLE
Accessibility - Need to Improve Heading Text on Step Topic Screens

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Ilab-do-good#61]
When looking at the Step 7 Topic 1 screen I noticed you have the text "Example In Action" three times. To a screen reader user they will think they are the same place because the text is the same.

To correct the issue add a number to each one if there is more than one on this or other screens. An example would be "Example In Action One", "Example In Action Two", and "Example In Action Three". You could change the word for the number to be the actual number but please follow the proper style rules that DOL has.

**Comment by adriennerlong** [comment]
John, we've asked ICF to change the headings for all examples in action to include the specific name of the example. Does that solve the problem?

**Comment by jfc3-dol** [comment]
@adriennerlong,

As long as they are not the same as other headings on the same page/screen.

**Comment by jfc3-dol** [comment]
@adriennerlong,

Of the screens I reviewed the two lines of text have been combined into one heading level two (h2) line of text.
