### ISSUE TITLE
Website - Home Page – Image of Girl Shows Her Feet

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Ilab-do-good#63]
When looking at the home page, the image of the young girl only displays her feet and the bottom of the sewing machine.

See attached screenshot.

![complychain - website - home page](https://user-images.githubusercontent.com/10423487/30119346-6553eeb6-92f3-11e7-92b0-66a7b53c132b.png)

**Comment by adriennerlong** [comment]
From ICF: Fixed

**Comment by jfc3-dol** [comment]
ComplyChain main screen image of the young girl now shows the entire image when using IE 11, Firefox 56, and Chrome 60.

Closing issue.
