### ISSUE TITLE
Website - Main Step 2 Page – Content Not Displayed

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Ilab-do-good#67]
Having all the content hidden is not the best experience users to find information about a subject. Similar issues for all the other main Step pages.

See screenshot below.

![complychain - step 2 - no visible content on page besides what look to be headings](https://user-images.githubusercontent.com/10423487/30120183-228ee290-92f6-11e7-8b32-e70ee63993e1.png)

**Comment by jfc3-dol** [comment]
The same issue occurs on all three platforms (iOS, Android, or Web).

**Comment by adriennerlong** [comment]
From ICF: Fixed

**Comment by jfc3-dol** [comment]
On the iOS version, I only see the "Topics" section expanded.

A visual user might not think to open the sections because they assume there is no content for the other sections.

VoiceOver does announce to the screen reader they can "toggle to expand content" or something like that.

Will check to see if the same applies to the Android and web version once they are deployed.

**Comment by jfc3-dol** [comment]
On the Android version, I only see the "Topics" section expanded.

A visual user might not think to open the sections because they assume there is no content for the other sections.

TalkBack does announce to the screen reader they can "click to expand content not checked. Double tap to toggle" or something like that. I would expect it to say "tap" or "double tap to expand content not checked. Double tap to toggle."

Will check to see if the same applies to the iOS and web version once they are deployed.

**Comment by jfc3-dol** [comment]
On the web version, I only see the "Topics" section expanded.

A visual user might not think to open the sections because they assume there is no content for the other sections.

JAWS does announce to the screen reader they can "click to expand content toggle button" or something like that.

**Comment by jfc3-dol** [comment]
Closing issue because ILAB does not plan to show all content when a person goes to those pages for all three platforms (web, iOS, and Android).
