### ISSUE TITLE
Website - Step 2 Topic 2 Page – Content Displays Across Entire Screen

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Ilab-do-good#68]
There should be a maximum width set for the screen's content. Doing so makes it easier to read than having to have text fill the screen. Having a smaller width screen will help with reading speed and comprehension for most users. Plus, be even better for those with reading issues or low vision.

Column width is recommended to be two to three alphabets or 52 – 78 characters wide. See screenshot that shows width closer to 78 characters.

Full screen width of text

![complychain - website step 2 topic 2 content dispalying over entire screen](https://user-images.githubusercontent.com/10423487/30120288-676cdc82-92f6-11e7-8c40-2163b61ecf30.png)

Narrow screen width of text to show better reading

![complychain - website - column width for eaier reading](https://user-images.githubusercontent.com/10423487/30120304-7066a17e-92f6-11e7-909a-b9755128f0ea.png)

**Comment by adriennerlong** [comment]
ICF, please make the width more narrow.

**Comment by jfc3-dol** [comment]
Thanks, for making the text only span part of the screen while it's centered.

Closing issue.
