### ISSUE TITLE
Side Swipe Issue with Basics of Social Compliance System

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Ilab-do-good#7]
Why when I swipe to move down the screen does the Basics of Social Compliance System does the screen go from left to right and back again.

This might be an issue on other screen too. Please check that there are no other ones.

**NOTE** - My testing is being done on our iPad Air 2 (iOS 10.3.3) because our iPod Touch 5th Generation (iOS 9.3.5) opens the application but displays a blank screen.

**Comment by adriennerlong** [comment]
The developers are aware of this problem. It seems to be occurring on all pages that have long, un-wrapped URLs. Please close out on this issue in the next testing.

**Comment by jfc3-dol** [comment]
@adriennerlong,

okay, as a rule we will close issue once we see that it is fixed.

**Comment by jfc3-dol** [comment]
The issue is working correctly, so I'm closing the issue.
