### ISSUE TITLE
Website - Accessibility - There are Two Tab Stops for Each Step Link in Main Menu

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Ilab-do-good#71]
After opening up the main menu and then the Steps section the keyboard only user and screen reader user has to tab or listen to two items for each step.

Why not make the text and the arrow one item so it's easier for both the keyboard only and screen reader users?

**Comment by JckICF** [comment]
The arrow item brings up the list of topics for a given step.  Should I change the button's label to clarify what it does?  (The hierarchy goes [link to step page, list of steps], [go back, {link to step, list of topics}], [go back, {topics}])

**Comment by adriennerlong** [comment]
John, please advise ICF what your preference is here.

**Comment by jfc3-dol** [comment]
@JckICF,

When I tab to through the open main menu I see a blue highlight line around the Step and number, then I tab a gain, and it highlights the Step and number along with the arrow. Didn't realize it had two different functions.

I think if the one opens the main Step page and the arrow opens or closes the Topic list the highlight should only go around the arrow or the Step and number instead of both.

Hope I explained that enough to make sense.

**Comment by adriennerlong** [comment]
From ICF: Fixed

**Comment by jfc3-dol** [comment]
Will review this issue once the latest web based version of ComplyChain is deployed.

**Comment by jfc3-dol** [comment]
JAWS reads each Step link as a separate link. The first says "Step" and it's number. The other tells the user that is toggle link/button can open to show the Topic for a given Step.

Going to remove the web label and close the issue.
