### ISSUE TITLE
Website - Accessibility - Why Can't People Open Step Topics with a Keyboard

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Ilab-do-good#73]
Why can't a keyboard only or screen reader user not open the different Topics under each Step using a keyboard?

**Comment by jfc3-dol** [comment]
It looks like it work when using the ENTER key and not the SPACE BAR.

Let me test a bit more from a few other pages.

**Comment by JckICF** [comment]
Hi, in my research, I was informed that links, and objects that are supposed to act like links should attempt to receive the ENTER key, but not the SPACE BAR to induce a page change.  Please let me know if this is incorrect.

**Comment by jfc3-dol** [comment]
@JckICF,

Yes, you are correct I guess I was having a moment and mixed up which keys to use with bouncing back and forth from application and device, etc.

Closing issue.
