### ISSUE TITLE
Functional - iPod Shows Steps 7 and 8 Icons

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Ilab-do-good#76]
When attempting to look at the ComplyChain application on our iPod model - ME643LL/A instead of displaying the home/main screen it shows the Steps wheel and only Steps 7 and 8 in portrait mode and Steps 1 and 8 in landscape mode.

You can use your finger to move around the screen to see each step. Tapping on them doe snot take you to the particular Step.

**Comment by jfc3-dol** [comment]
On the iPad you can see all the icons but it should be showing the home screen with the young girl. Also, the icons are not active and can't be used to go to the Step detail screens.

**Comment by adriennerlong** [comment]
From ICF: Unsure on how to resolve.  Features required may not be supported by that model. 

From ILAB: Can we put a disclaimer in the iTunes store that the app doesn’t work with certain versions of iOS?

**Comment by jfc3-dol** [comment]
@giridhar,

Isn't there a way for iTunes to only allow certain iOS versions to download the applications to prevent people from downloading an application that won't work?

**Comment by jfc3-dol** [comment]
When using our new iPhone 7 running 10.3.3, the application is working. It still has trouble with older devices but I'm still going to close the issue.
