### ISSUE TITLE
Website - Functional - Looking at Website in Safari Browser on the iPod Shows Steps 7 and 8 Icons Only

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Ilab-do-good#77]
When attempting to look at the ComplyChain website in the Safari browser on our iPod (model - ME643LL/A) instead of displaying the home/main screen it shows the Steps wheel and only Steps 7 and 8 in portrait mode and Steps 1 and 8 in landscape mode.

You can use your finger to move around the screen to see each step. 

Tapping on them doe snot take you to the particular Step.

**Comment by jfc3-dol** [comment]
Similar for looking at the website version on the iPad but you see more of the icons.

**Comment by adriennerlong** [comment]
From ICF: Unsure on how to resolve. Features required may not be supported by that model.

From ILAB: Can we put a disclaimer in the iTunes store that the app doesn’t work with certain versions of iOS?

**Comment by jfc3-dol** [comment]
@giridhar,

Isn't there a way for iTunes to only allow certain iOS versions to download the applications to prevent people from downloading an application that won't work?

**Comment by jfc3-dol** [comment]
When using our new iPhone 7 running 10.3.3, the application is working. It still has trouble with older devices so going to remove the iOS label and check Android and the web versions when I get a chance.

**Comment by jfc3-dol** [comment]
The application works with the newer iOS and Android devices. The web version works with IE 11, Firefox 56, and Chrome 60.

Removing the web label and closing the issue.
