### ISSUE TITLE
Heading Structure Question

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Ilab-do-good#8]
Why on some of the screens do you un-ordered lists with only one item that is a link when it most likely should be a heading to help people see the different main sections on the page.

Please see the following screens as an example.

- What are Child and Forced Labor
- Why Develop a Social Compliance System?
- The Basics of a Social Compliance System

Will add more screens and screenshot as I test and find them.

The same issue seems to apply to all the different Steps Topics screens too. I'm currently, looking at the Step 4 Topic 3 of 6 screen.

**NOTE** - My testing is being done on our iPad Air 2 (iOS 10.3.3) because our iPod Touch 5th Generation (iOS 9.3.5) opens the application but displays a blank screen.

**Comment by adriennerlong** [comment]
We made this design choice in the interest of time. We would definitely like to prioritize formatting in the next iteration of this app. Also, please note that much of the text that is current hyperlinked is not actually supposed to be hyperlinked. We provided final text to the developers and they are incorporating for the next testing. Please close out this issue.

**Comment by jfc3-dol** [comment]
@adriennerlong,

Visually impaired users use headings to navigate the page so they can move from one section to another as a sighted person would use to scan the page.

It's a necessary way for them to move around a screen especially when it's a few screens long to see if there is any information they want to find.

**Comment by jfc3-dol** [comment]
The issue has been corrected, so I'm closing the issue.
