### ISSUE TITLE
Functional - Step 2 Topic 5 - All Text after "Example in Action:..." is Bold

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Ilab-do-good#81]
All the text after the heading level two (h2) of "Example in Action: The Important Role of Media Reporting" is bold.

My guess is there is an open BOLD or STRONG tag that wasn't closed or maybe a DIV or SPAN.

**Comment by jfc3-dol** [comment]
The issue applies to all three platforms (iOS, Android, and web).

**Comment by adriennerlong** [comment]
From ICF: Fixed

**Comment by jfc3-dol** [comment]
In iOS, the text after the "Example in Action:..." heading is no longer bold.

Removing the iOS label and will do the same for the Android and web versions once I can check them.

**Comment by jfc3-dol** [comment]
In Android, the text after the "Example in Action:..." heading is no longer bold.

Removing the Android label and will do the same for the Android and web versions once I can check them.

**Comment by jfc3-dol** [comment]
In web version, the text after the "Example in Action:..." heading is no longer bold.

Removing the web label and going to close the issue..
