### ISSUE TITLE
Functional - Step 2 Topic 4 - "Previous Topic" and "Next Topic" Buttons Jammed Up Against Light Blue Box Above

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Ilab-do-good#82]
The "Previous Topic" and "Next Topic" buttons are jammed up against the light blue background section above them.

**Comment by jfc3-dol** [comment]
Issue applies to both iOS and Android along with the website.

**Comment by adriennerlong** [comment]
From ICF: Fixed

**Comment by jfc3-dol** [comment]
In iOS, the buttons now seem to have some space between them and the images at the bottom of the page.

Removing the iOS label because it seems to be fixed but leaving the other on until I can check them.

**Comment by jfc3-dol** [comment]
The buttons now seem to have some space between them and the images at the bottom of the page.

Removing the Android label and going to check the website version once that is ready for me to test.

**Comment by jfc3-dol** [comment]
The buttons now seem to have more space between them and the images at the bottom of the page.

Removing the web label and going to close the issue.
