### ISSUE TITLE
Accessibility - TalkBack Reads Topic Links in Menu Twice

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Ilab-do-good#84]
While using TalkBack to read the main menu it reads the Topics twice for some reason which is not expected.

**Comment by adriennerlong** [comment]
From ICF: Unfixed.  Current solution unknown.  Differences in screen readers are causing trouble.

**Comment by jfc3-dol** [comment]
Will review this issue once the latest Android version of ComplyChain is deployed to my devices.

**Comment by jfc3-dol** [comment]
TalkBack now reads the main Step and number as one link and the next one as a link to display the list of Topics for that Step.

Closing issue since it fixes the initial problem.
