### ISSUE TITLE
Accessibility - Having Difficulty Opening the Toggled Topics in the Main Steps Screens with TalkBack

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Ilab-do-good#85]
While using the screen reader TalkBack on the Android device it's difficult to open the toggled items partially because it does not tell you which one you are at and sometimes they don't open when double tapped.

**Comment by adriennerlong** [comment]
From ICF: Unfixed.  Needs testing.

**Comment by jfc3-dol** [comment]
Will review this issue once the latest Android version of ComplyChain is deployed to my devices.

**Comment by jfc3-dol** [comment]
I can open the different sections with TalkBack which informs me as a screen reader user that there is hidden content. It does not allow me to double tap a second time to close it if I meant not to open it as the iOS version does.

Closing issue because it seems to have fixed the initial problem.
