### ISSUE TITLE
Accessibility - Not Able to Type in Search Box on Android with TalkBack

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Ilab-do-good#86]
I'm not able to type in the search box using TalkBack.

**Comment by adriennerlong** [comment]
From ICF: Unfixed. Needs testing.

**Comment by jfc3-dol** [comment]
Will review this issue once the latest Android version of ComplyChain is deployed to my devices.

**Comment by jfc3-dol** [comment]
I am now able to type in the search INPUT field when TalkBack is active.

Going to close the issue.
