### ISSUE TITLE
Functional - Website - Home Page Image to Large (4MB) 

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Ilab-do-good#89]
While loading the ComplyChain home page ( https://dolcontentdev.opadev.dol.gov/ilab/complychain/ ) I noticed the image of the young women behind the sewing machine was loading slowly. On further inspection, I found the image is 4MB in size. 

To make the page load quicker, I would assume if the image was "Saved for web" along with downgrading the quality a little bit should get it to be a few hundred KBs.

I am assuming this image is used for the iOS and Android applications too. So making it smaller for the webs will make the applications load faster too.

**Comment by sanganalakshay** [comment]
should be fixed

**Comment by jfc3-dol** [comment]
Will test when we get the next code push.

**Comment by jfc3-dol** [comment]
Looked at the young woman at the sewing machine image and it is now about 365 KB instead of almost 4 MB.

I'm going to close this issue.
