### ISSUE TITLE
Functional - Web - Main Steps Image Text Not in French

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Ilab-do-good#94]
The Steps background image needs a version with text for French. The text that shows up when you hover is only in English on the French web page. The pop-up text/image only show when you hover with a mouse to tell you what the step is supposed to be. It should also show when a person uses a keyboard. Not sure if the pop-ups are created with text or an image so you might want to look at making images for that too. I know JAWS is reading them all in English even though they are supposed to be in French on the web page.

**Comment by sanganalakshay** [comment]
fixed

**Comment by jfc3-dol** [comment]
The main Steps icon/graphic now has French text in the center and the same for the individual steps.

See the screenshot below.

![complychain - web - french - main steps image is in french](https://user-images.githubusercontent.com/10423487/43418743-e9eaf2ee-940c-11e8-8989-3c9ec094e01f.png)

Closing issue.
