### ISSUE TITLE
Functional - iOS- Main Steps Image Text Not in French

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Ilab-do-good#95]
The Steps background image needs a version with text for French. The text that shows up when you hover is only in English on the French screen.  I know VoiceOver is reading them all in English even though they are supposed to be in French on the screen.

**Comment by sanganalakshay** [comment]
fixed

**Comment by jfc3-dol** [comment]
The Steps image is now in French when the language is set to French.

The pop-up text to tell the user what each set is working when tapped. Need to double tap to go to the detail screen for a given step.

Closing issue. Will check later if VoiceOver reads the pop-ups of not if not will open an issue.
