### ISSUE TITLE
Accessibility - Web - Steps Pop-ups Only Not in Spanish

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Ilab-do-good#97]
When the users has changed languages to Spanish the pop-up text/image only show up in English. Not sure if the pop-ups are created with text or an image so you might want to look at making images for that too.

**Comment by sanganalakshay** [comment]
fixed

**Comment by jfc3-dol** [comment]
The individual Topic pop-ups on the main Steps page are now in Spanish when the language is set to Spanish.

See the screenshot below.

![complychain - web - spanish - main steps image is in spanish](https://user-images.githubusercontent.com/10423487/43421031-894dd6ac-9413-11e8-8d66-c401c2e7fba4.png)

Closing issue.
