### ISSUE TITLE
Accessibility - Web - Steps Pop-ups Only Not in French

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Ilab-do-good#98]
When the users has changed languages to French the pop-up text/image only show up in English. Not sure if the pop-ups are created with text or an image so you might want to look at making images for that too.

**Comment by sanganalakshay** [comment]
fixed

**Comment by jfc3-dol** [comment]
The individual Topic pop-ups on the main Steps page are now in French when the language is set to French.

See the attached screenshot.

![complychain - web - french - main steps image is in french](https://user-images.githubusercontent.com/10423487/43421208-0ef41028-9414-11e8-9565-1ed1dae1acc0.png)

Closing Issue.
