### ISSUE TITLE
Accessibility - Web - Steps Pop-ups Only Activated with Hover

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Ilab-do-good#99]
The pop-up text/image only show when you hover with a mouse to tell you what the step is supposed to be. It should also show when a person uses a keyboard by tabbing to them. The problem occurs for the English, Spanish, and French versions of the page.

**Comment by sanganalakshay** [comment]
fixed

**Comment by jfc3-dol** [comment]
The English, Spanish, and French pages work in IE 11. Can not tab to the individual Step items in Chrome. Firefox won't even load the application.

So it's getting better.

Even IE gets a "Loading Resources..." spinning icon at the top of the page with the rest below it. 

See the attached screenshot. Will create a separate issue for this problem.

![complychain - firefox - home page](https://user-images.githubusercontent.com/10423487/43530775-6135d1c8-957c-11e8-9c20-6b7ff7a606b2.png)

**Comment by sanganalakshay** [comment]
which version of Internet explorer are you running ?

**Comment by jfc3-dol** [comment]
Sorry, I'm using IE 11.0.9

**Comment by jfc3-dol** [comment]
On the previous version I was able to load the application in IE 11, Chrome, and Firefox. Will update the none loading gitHub issue with this information.

**Comment by jfc3-dol** [comment]
There is now a visual pop-ups for the individual Steps on the English, Spanish, and French main Steps page for IE 11, Firefox, and Chrome.

I'm going to close this issue.
